### ISSUE TITLE
Design of multimeter is not very compact

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-android#1003]
**Actual Behaviour**

The design of multimeter looks good for smaller screens but causes problem in bigger screens. Also the knob doesn't give same look as that on hardware device

**Expected Behaviour**

Above issues shouldn't be there

**Steps to reproduce it**

Go to multimeter instrument and analyze it

**LogCat for the issue**

Not applicable

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
@harsh-2711 can you post an image of the changes you made? Also focus on the device assigned to you first and make it fully complete! :+1:

**Comment by cweitat** [comment]
Have a look at how a multimeter designs. Instead of sectioning 4 sides, you can indicate different sections with different font colour, like red and black,  alternately. 
![photo_2018-06-13_02-53-38](https://user-images.githubusercontent.com/11439477/41310732-f6fa6c4e-6eb4-11e8-9b7a-277b807ff5fb.jpg)

Also, as mentioned, the text positioning covering the knob. When I press the text, the knob should turn to it; this function currently has some bugs and doesn't works the same for all.

**Comment by cweitat** [comment]
@abhinavraj23
