### ISSUE TITLE
Logic Analyzer UI

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#142]
Coding UI for Logic Analyzer by taking reference from [LAmockup](https://app.moqups.com/viveksbhadauria007@gmail.com/Xz2hJPtEc5/view) here.

- [x] UI for channel select whether Single Channel Mode, Two Channel Mode, etc
- [ ] UI for showing Logic Lines from channel selected and configured in previous fragment [WIP]

**Comment by viveksb007** [comment]
![screenshot_2017-06-11-13-11-55-284_org fossasia pslab](https://user-images.githubusercontent.com/12713808/27009344-f532e03a-4ea8-11e7-9a8c-8230736f76a2.png)

Used different charts for different logic lines.
Here is a link for video that I made by changing parameters. Would add a slider panel to change input channel and edge select on Logic Lines Screen. Would look into plotting logic line as ideal logic line i.e both high and low at same time during transition. Its default plotting of MPAndroidChart.

https://goo.gl/photos/axoymdEgzHQBnyFK7

@jithinbp @akarshan96 @asitava1998 @CloudyPadmal have a look and provide review comments. Thanks

**Comment by jithinbp** [comment]
@viveksb007 thank you. My thoughts : 
-  It's a lot easier to view multi-channel logic signals if the X-Axes are linked together. Scaling the time axis of one plot, while the others stay the same is misleading.
-  I see you've used a sample dataset that changes the level periodically. Issues that should be noted:
    - The Logic Analyzer functions only tell you when the logic level changed. There are no datapoints if the level did not change. 
    - For each level change, you need to generate two datapoints to draw a vertical line:[ (timestamp, Y_OFFSET), (timestamp,Y_OFFSET+height_of_channel ) ] or vice versa .   Y_OFFSET depends on the channel number  .   If you ported digital_channel.py completely , this has already been done.

Here's a screenshot of the implementation in pslab-desktop-apps. It's an early revision, so ignore the axis labels and stuff. But otherwise it conveys a clear picture of the logic states, and zooming along the X direction will easily reveal time-critical details.
![scope_la](https://user-images.githubusercontent.com/6078658/27009553-fb1cba10-4eae-11e7-82a6-9a4076c227e2.png)


And here's a screenshot from a commercial app. Looks like Saleae's app, but I'm not sure.

![](http://dani.foroselectronica.es/wp-content/uploads/2010/11/spi_ping_la.png)

**Comment by viveksb007** [comment]
@jithinbp Thanks for the review. 
So to solve this I am thinking of using a single chart and clamping signals from different channels at different y-offsets. Need to take care of labels on Y-axis. Would that be okay?
And when logic analyzer would return a list of timestamps and initial state, I would generate data points accordingly. This data-point sample was generate just to show plotting of logic lines.
Interchanging of stacking of charts might be difficult, but would look into it after basic functionality is done.
I will put updated screenshots as soon as its done.

**Comment by viveksb007** [comment]
I have made the following changes:

- Plotted Ideal Logic Lines
- All plots are on same chart so, time axis change is same in all channels simultaneously
- Generated random timestamps for plotting data.

ToDo 

- Need to take care of Labels on Y-Axis.

Link for new ScreenCast : https://goo.gl/photos/j31ZZvy9AN3LQzt47
@jithinbp could you have another look please?
Thanks
