### ISSUE TITLE
New instrument : Thermometer

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1629]
**Actual Behaviour**

There is no device to calculate temperature in the app.

**Expected Behaviour**

Using the inbuilt android ambient temperature sensor , create a thermometer.

**Steps to reproduce it**

Not applicable

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes .

**Comment by neel1998** [comment]
@ho-dor  this might not be very much useful since very few smartphones out there have external temperature sensor. All phones have internal temperature sensor for the main chip, but external temperature sensor is not provided with most of the smart phones. @harsh-2711  @mariobehling  kindly share your views on this issue

**Comment by ho-dor** [comment]
This is same for gyroscope or the magnetic sensor which isn't present in Samsung J8 and I think some other devices as well

**Comment by neel1998** [comment]
@ho-dor  looking at the statistics of the the sensors in the amar phones currently in market . Very very small percent provide ambient temperature sensor. However number of smart phones having gyroscope is very large. Still you can implement this feature. There nothing to lose having more feature :)

**Comment by ho-dor** [comment]
@mariobehling please give your views on this new instrument .

**Comment by CloudyPadmal** [comment]
Hello @ho-dor , Thermometer would be a good idea. We are not focusing on sensors in Android phone but the sensors that can be connected with PSLab externally. I think [LM35](www.ti.com/lit/ds/symlink/lm35.pdf) would be a better candidate for this. Could you please provide us with some mockups? Thanks. If a device has a thermometer inbuild, we can let user select which one to chose.

**Comment by ho-dor** [comment]
@CloudyPadmal sure . I will let you know soon.

**Comment by ho-dor** [comment]
@CloudyPadmal can you take a look at SHT21 sensor already used in the app , can I use that in place of LM35 ?

**Comment by CloudyPadmal** [comment]
Yea that would be ok. But we can let user choose which sensor to use and give an option to switch between sensors. You can start with anything you like.

**Comment by neel1998** [comment]
@ho-dor  Are you planning on adding a new instrument activity or making changes in the sensors activity?

**Comment by ho-dor** [comment]
@neel1998 for now , a new instrument activity.

**Comment by neel1998** [comment]
@ho-dor  I think it would be better to have it in sensors activity. Because i still think most of the mobiles don't have external temperature sensor. And those wit the PSLab board can use the sensor from the sensor activity. @CloudyPadmal  kindly share your opinion. I think we should have separate instrument activities for those sensors which are more likely to be present in more android devices

**Comment by ho-dor** [comment]
@neel1998 but we are going to give option to the user to choose the inbuilt device sensor or through the PSLab device .

**Comment by neel1998** [comment]
@ho-dor  alright :). Let me know if you need any help
