### ISSUE TITLE
'Not Connected' toast message repeatedly keeps popping up in Dust Sensor

### ISSUE THREAD

**Issue by reckoner1429** [fossasia/pslab-android#2000]
**Actual Behaviour**

When dust sensor is not connected, the **not connected** toast message keeps popping up repeatedly.

**Expected Behaviour**

The **not connected** message must not keep flashing  before the screen just like it is in other sensors where the message is displayed only once

**Steps to reproduce it**

- Do not connected the USB device and then open the Dust Sensor

**LogCat for the issue**

>N/A

**Screenshots of the issue**

![toast_issue4](https://user-images.githubusercontent.com/13999905/68527090-27783600-0309-11ea-87ff-34c044642fbf.jpeg)

**Would you like to work on the issue?**

Yes

**Comment by shreyansjain012** [comment]
Hi. Is this issue assigned to someone else? I would live to work on it

**Comment by adityastic** [comment]
@shreyansjain012 we might need input from @reckoner1429 atm

**Comment by reckoner1429** [comment]
@shreyansjain012 and @adityastic , I also want this issue to be assigned to me, however I have not received any word from the repository maintainers. 
PS - This is my first attempt at open source contributions so i am not very well aware about how long will i have to wait to receive a word from the maintainers

**Comment by neel1998** [comment]
@reckoner1429 since you have raised the issue and also mentioned you would like to work on it there is no need for you to wait for the maintainers to assign the issue to you. You can start working on it and make the PR. Please refer to the readme for contributors and follow the best practices . Cheers.

**Comment by shreyansjain012** [comment]
@reckoner1429 @adityastic I am new to open source I think I have the code ready which is working fine but I don't know how to proceed from here? Should I wait for someone to assign it or just submit a pull request?

**Comment by neel1998** [comment]
@shreyansjain012 it's great that you have solved this issue but since the author of the issue already mention that he would like to work on it is not good practice to file a PR until the author says he is not gonna work on it anymore. In this case @reckoner1429 if is not going to work on this issue anymore you can file a PR

**Comment by shreyansjain012** [comment]
@neel1998 Okay. Thanks.

**Comment by reckoner1429** [comment]
@neel1998 Thanks a lot for the directions! I am now working on this issue.
