### ISSUE TITLE
Oscilloscope UI

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#33]
This is the first step towards the development Oscilloscope's UI.

![screenshot_1491903305](https://cloud.githubusercontent.com/assets/26146675/24909282/e740fb8a-1ee0-11e7-8c0e-0d195c77727d.png)

![screenshot_1491903314](https://cloud.githubusercontent.com/assets/26146675/24909283/ea1a03a6-1ee0-11e7-8d23-71eefb170c16.png)

The above image showcase the landscape mode of the Oscilloscope Activity. 
Gestures will also be integrated, like
-pinch zoom for changing the timebase.
-double tap on the graph to freeze.
-swipe down to save.

Please give suggestions on:
-layout and what needs to be improved.
-real-time graph api to be used ( I have used GraphView http://www.android-graphview.org). We can also use MPAndroidChart https://github.com/PhilJay/MPAndroidChart).
-I have researched on 3D graphs libraries but they are paid.
-any other thing I missed.

**Comment by akarshan96** [comment]
![screenshot_1491739737](https://cloud.githubusercontent.com/assets/26146675/24837189/bb19e5e4-1d4b-11e7-9ca9-6d7029e78bb8.png)

This is the screenshot of Oscilloscope Activity running on a 7inch tablet.

**Comment by asitava1998** [comment]
I think we can add the various types of trigger modes found in the oscilloscopes used in Labs. They are as follows:-
A. Auto -  This trigger mode allows the oscilloscope to acquire a waveform even when it does not detect a trigger condition. If no trigger condition occurs while the oscilloscope waits for a specific period (as determined by the time-base setting), it will force itself to trigger.
B. Normal -  The Normal mode allows the oscilloscope to acquire a waveform only when it is triggered. If no trigger occurs, the oscilloscope will not acquire a new waveform, and the previous waveform, if any, will remain on the display.
C. Single -  The Single mode allows the oscilloscope to acquire one waveform each time you press the RUN button, and the trigger condition is detected.
D. Scan – The Scan mode continuously sweeps waveform from left to right.
I can implement these in the oscilloscope UI and these would help to make it more elaborate.

Another feature that I would like to suggest is automatic scaling of the graph. Suppose the graph has axes set between 0-100 units and then keeps receiving data between 0-50 units, we can automatically scale up the graph for better view instead of the user zooming into it.

**Comment by akarshan96** [comment]
@asitava1998 and I come up with an idea to have a bar at the bottom of the screen which shows the status of the device and other information like sampling rates etc.

images indicate that the PSLab is connected or disconnected
![img_3380](https://cloud.githubusercontent.com/assets/26146675/25779006/c64b78f6-332b-11e7-9e62-c477ef32254a.PNG)
![img_3381](https://cloud.githubusercontent.com/assets/26146675/25779007/c7f80e6c-332b-11e7-9ed1-242d813d4571.PNG)
