### ISSUE TITLE
Lack of guidance on how to connect a sensor to PSLab device

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#894]
**Actual Behaviour**

Existing Sensors instrument does not show the list of sensors that can be used with PSLab. Using the scan button, app will try to find if any sensor is attached or not. 

**Expected Behaviour**

It is better to show the compatible list of sensors in the Sensors activity and when selected, rather than showing a message that sensor is not connected, can include a pop-up screen to show how to connect the sensor to the PSLab. For each and every different sensor, there should be a clear image/gif on steps to connect the sensor to the PSLab.   

**Steps to reproduce it**

 > Not applicable

**LogCat for the issue**

> Not applicable

**Screenshots of the issue**

![screenshot_2018-05-22-00-48-25](https://user-images.githubusercontent.com/17523141/40326049-8eb9941c-5d5b-11e8-812d-7b220e7a1ebb.png)

**Would you like to work on the issue?**

Yes. But open to anyone as there are lot of sensors compatible with PSLab.

**Comment by cweitat** [comment]
Few solutions here:

1.  created a list tested by us
2.  let users add to the list directly
3.  let users submit the sensors number to us and we try it

On top of that, the list is best to be searchable by filters (e.g. type of sensors, alphabetical, etc) instead of just a scrollable one

Please discuss which is the best way to implement this

**Comment by CloudyPadmal** [comment]
Sensors will be implemented as individual instruments. There will be guides available in each sensor view with corresponding issues.
